services:
  mysql:
    image: mysql:latest
    container_name: mysql_inventory
    ports:
      - "3307:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD: mysql'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql